# Generated by Django 3.1.5 on 2021-01-14 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book_shelf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('edition', models.IntegerField(blank=True, max_length=5, null=True)),
                ('price', models.IntegerField(blank=True, max_length=8, null=True)),
            ],
        ),
    ]
